on:
  push:
    branches: main
    paths: editable/excerpt.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Java code used by this build
        run: wget --no-verbose https://ebookipedia.github.io/java/build.jar
      - name: Get target repository name (creating it if not exists)
        id: getTarget
        run: |
          export GITHUB_OAUTH=${{secrets.GITHUB_TOKEN}}
          java -cp build.jar repository.Target $GITHUB_REPOSITORY
          echo "output: $(<out/target)"
          echo ::set-output name=repository::$(<out/target)
      - uses: actions/checkout@v2
        with:
          path: source
      - uses: actions/checkout@v2
        with:
          repository: ${{steps.getTarget.outputs.repository}}
          path: target
      - run: | 
          # wget https://ebookipedia.github.io/java/build.jar
          java -cp https://ebookipedia.github.io/java/build.jar mirror.Wikipedia $GITHUB_REPOSITORY
          echo $(<out.article)
          if [ ! -f src/$(<out.article).epub ]; then
            sudo apt-get install mediawiki2latex
            mediawiki2latex --epub --url="$(< out.url)" --output="src/source.epub"
            git config --global user.name 'Santiago Ruiz'
            git config --global user.email 'hiebra@hotmail.com'
            git add src/source.epub
            git commit -m "epub generated by mediawiki2latex (ubuntu package)"
            git push
          fi
